[package]
name = "crypto"
version = "0.1.0"
edition = "2018"
authors = [
  "Pablo Aldape <pablo@vest.com>",
  "Lucas Ege <lucas@vest.com>",
  "Noah Golub <noah@vest.com>",
  "Sanjay Kannan <sanjay@vest.com>",
  "Eddie Wang <eddie@vest.com>"
]
description = "Accumulators and associated cryptographic primitives in Rust."
keywords = ["cryptography", "crypto", "accumulator", "rsa"]
readme = "README.md"
repository = "https://github.com/1protocol/crypto"

[dependencies]
bitvec = "0.9.0"
blake2-rfc = "0.2.18"
byteorder = "1.2.7"
criterion = "0.2.8"
gnuplot = "0.0.26"
lazy_static = "1.2.0"
num = "0.2.0"
num-bigint = "0.2"
num-integer = "0.1"
num-traits = "0.2"
rand = "0.6.4"
ring = { git = "https://github.com/1protocol/ring" }
untrusted = "0.6.2"

[[bench]]
name = "poe"
path = "benches/proof/poe.rs"
harness = false

[[bench]]
name = "poke"
path = "benches/proof/poke2.rs"
harness = false

[[bench]]
name = "pokcr"
path = "benches/proof/pokcr.rs"
harness = false

[[bench]]
name = "hashes"
path = "benches/hash/hashes.rs"
harness = false

[profile.dev]
opt-level = 3
