[package]
name = "crypto"
version = "0.1.0"
authors = ["Eddie Wang <eddie@vest.com>, add yourselves here"]
edition = "2018"

[dependencies]
alga = "0.7.2"
bigint = "4.4.1"
num = "0.2.0"
ring = "0.14.1"
