[package]
name = "crypto"
version = "0.1.0"
edition = "2018"
authors = [
  "Pablo Aldape <pablo@vest.com>",
  "Lucas Ege <lucas@vest.com>",
  "Sanjay Kannan <sanjay@vest.com>",
  "Eddie Wang <eddie@vest.com>"
]

[dependencies]
alga = "0.7.2"
bigint = "4.4.1"
num = "0.2.0"
ring = "0.14.1"
