[package]
name = "crypto"
version = "0.1.0"
edition = "2018"
authors = [
  "Pablo Aldape <pablo@vest.com>",
  "Lucas Ege <lucas@vest.com>",
  "Sanjay Kannan <sanjay@vest.com>",
  "Eddie Wang <eddie@vest.com>"
]
description = "Accumulators and associated cryptographic primitives in Rust."
keywords = ["cryptography", "crypto", "accumulator", "rsa"]
readme = "README.md"
repository = "https://github.com/1protocol/crypto"

[dependencies]
alga = "0.7.2"
uint = "0.6.1"
blake2-rfc = "0.2.18"
num = "0.2.0"
ring = "0.14.1"
sha2 = "0.8.0"